name: Playwright test
on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Archive test artifacts
        run: |
          mkdir -p test-results/screenshots
          mkdir -p test-results/recordings
          cp -R screenshots test-results/
          cp -R recordings test-results/
        continue-on-error: true

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results
